server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  h2:
    console:
      enabled: 'true'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/artembelysev
    username: postgres
    password': postgres